name = "Sling Load Rigging"
prefix = "slr"
mainprefix = "z"

[properties]
author = "Ampersand"
url = "https://github.com/ampersand38/sling-load-rigging"

[files]
include = [
    "AUTHORS.txt",
    "LICENSE",
    "logo_ampersand_ca.paa",
    "mod.cpp",
    "README.md"
]

[asc]
enabled = true
